### ISSUE TITLE
no first class handling added

### ISSUE THREAD

**Issue by wkdwich** [Evan-R/USPS-osCommerce#2]
All other features appear to be working, rates pulled - extra services has NOT been tested

this module is not adding First Class handling fees.

running 
  oscMax v2.5x
 USPS Methods http://addons.oscommerce.com/info/487  v5.2

**Comment by Evan-R** [comment]
I tentatively recommend that you upgrade to the 7.X version:
https://github.com/Evan-R/USPS-osCommerce/releases

However, please note that not all methods have been verified, so you should verify methods and rates before activating. If you would like to test rates / update the contribution, feel free to make a pull request :)
