### ISSUE TITLE
handling fees

### ISSUE THREAD

**Issue by wkdwich** [Evan-R/USPS-osCommerce#4]
All handling fees - domestic & international - seem to be added except domestic First Class Mail.
Additionally First Class Mail shows no expected delivery information:

First-Class Mail
---Approx. delivery time [SHOULD BE SOMETHING HERE]  $2.32  
 Media Mail
---Approx. delivery time 10-14 business days $4.08  
 Standard Post
---Approx. delivery time 6-12 business days $7.70

**Comment by Evan-R** [comment]
you might want to try 7.1.0; I've ceased maintenance work on 5.x, but I'll leave this issue open in case anyone else wants to fix it
