### ISSUE TITLE
-2147219101 Missing value for Service.

### ISSUE THREAD

**Issue by naps1saps** [Evan-R/USPS-osCommerce#6]
I was the first person to convert this contribution to API v3 but it has gotten so complicated since then I can't figure it out lol.
can't get any domestic shipping services
if i change the types array to what i had previously i get some domestic services like parcel post but no letters, etc. which is my main container type for stickers.  Not sure why it makes any difference but it does:

$this->types = array(
      'Express Mail' => 'Express Mail<sup>&reg;</sup>',
      'Express Mail Hold For Pickup' => 'Express Mail<sup>&reg;</sup> Hold For Pickup',
      'Express Mail Flat Rate Boxes' => 'Express Mail<sup>&reg;</sup> Flat Rate Boxes',
      'Express Mail Flat Rate Boxes Hold For Pickup' => 'Express Mail<sup>&reg;</sup> Flat Rate Boxes Hold For Pickup',
      'Express Mail Flat Rate Envelope' => 'Express Mail<sup>&reg;</sup> Flat Rate Envelope',
      'Express Mail Flat Rate Envelope Hold For Pickup' => 'Express Mail<sup>&reg;</sup> Flat Rate Envelope Hold For Pickup',
      'Express Mail Legal Flat Rate Envelope' => 'Express Mail<sup>&reg;</sup> Legal Flat Rate Envelope',
      'Express Mail Legal Flat Rate Envelope Hold For Pickup' => 'Express Mail<sup>&reg;</sup> Legal Flat Rate Envelope Hold For Pickup',
      'Express Mail Padded Flat Rate Envelope' => 'Express Mail<sup>&reg;</sup> Padded Flat Rate Envelope',
      'Express Mail Padded Flat Rate Envelope Hold For Pickup' => 'Express Mail<sup>&reg;</sup> Padded Flat Rate Envelope Hold For Pickup',
      'Priority Mail' => 'Priority Mail<sup>&reg;</sup>',
      'Priority Mail Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Hold For Pickup',
      'Priority Mail Large Flat Rate Box' => 'Priority Mail<sup>&reg;</sup> Large Flat Rate Box',
      'Priority Mail Large Flat Rate Box Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Large Flat Rate Box Hold For Pickup',
      'Priority Mail Medium Flat Rate Box' => 'Priority Mail<sup>&reg;</sup> Medium Flat Rate Box',
      'Priority Mail Medium Flat Rate Box Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Medium Flat Rate Box Hold For Pickup',
      'Priority Mail Small Flat Rate Box' => 'Priority Mail<sup>&reg;</sup> Small Flat Rate Box',
      'Priority Mail Small Flat Rate Box Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Small Flat Rate Box Hold For Pickup',
      'Priority Mail Regional Rate Box A' => 'Priority Mail<sup>&reg;</sup> Regional Rate Box A',
      'Priority Mail Regional Rate Box A Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Regional Rate Box A Hold For Pickup',
      'Priority Mail Regional Rate Box B' => 'Priority Mail<sup>&reg;</sup> Regional Rate Box B',
      'Priority Mail Regional Rate Box B Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Regional Rate Box B Hold For Pickup',
      'Priority Mail Regional Rate Box C' => 'Priority Mail<sup>&reg;</sup> Regional Rate Box C',
      'Priority Mail Regional Rate Box C Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Regional Rate Box C Hold For Pickup',
      'Priority Mail Flat Rate Envelope' => 'Priority Mail<sup>&reg;</sup> Flat Rate Envelope',
      'Priority Mail Flat Rate Envelope Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Flat Rate Envelope Hold For Pickup',
      'Priority Mail Legal Flat Rate Envelope' => 'Priority Mail<sup>&reg;</sup> Legal Flat Rate Envelope',
      'Priority Mail Legal Flat Rate Envelope Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Legal Flat Rate Envelope Hold For Pickup',
      'Priority Mail Padded Flat Rate Envelope' => 'Priority Mail<sup>&reg;</sup> Padded Flat Rate Envelope',
      'Priority Mail Padded Flat Rate Envelope Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Padded Flat Rate Envelope Hold For Pickup',
      'Priority Mail Gift Card Flat Rate Envelope' => 'Priority Mail<sup>&reg;</sup> Gift Card Flat Rate Envelope',
      'Priority Mail Gift Card Flat Rate Envelope Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Gift Card Flat Rate Envelope Hold For Pickup',
      'Priority Mail Small Flat Rate Envelope' => 'Priority Mail<sup>&reg;</sup> Small Flat Rate Envelope',
      'Priority Mail Small Flat Rate Envelope Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Small Flat Rate Envelope Hold For Pickup',
      'Priority Mail Window Flat Rate Envelope' => 'Priority Mail<sup>&reg;</sup> Window Flat Rate Envelope',
      'Priority Mail Window Flat Rate Envelope Hold For Pickup' => 'Priority Mail<sup>&reg;</sup> Window Flat Rate Envelope Hold For Pickup',
      'First-Class Mail Parcel' => 'First-Class Mail<sup>&reg;</sup> Parcel',
      'First-Class Mail Large Envelope' => 'First-Class Mail<sup>&reg;</sup> Large Envelope',
      'First-Class Mail Letter' => 'First-Class Mail<sup>&reg;</sup> Letter',
      'First-Class Package Service' => 'First-Class<sup>&trade;</sup> Package Service',
      'First-Class Package Service Hold For Pickup' => 'First-Class<sup>&trade;</sup> Package Service Hold For Pickup',
      'Standard Post' => 'Standard Post<sup>&reg;</sup>',
      'Media Mail' => 'Media Mail<sup>&reg;</sup>',
      'Library Mail' => 'Library Mail'
    );
    $this->type_to_request = array(
      'Express Mail' => 'Express Commercial',
      'Express Mail Hold For Pickup' => 'Express HFP Commercial',
      'Express Mail Flat Rate Boxes' => 'Express Commercial',
      'Express Mail Flat Rate Boxes Hold For Pickup' => 'Express HFP Commercial',
      'Express Mail Flat Rate Envelope' => 'Express Commercial',
      'Express Mail Flat Rate Envelope Hold For Pickup' => 'Express HFP Commercial',
      'Express Mail Legal Flat Rate Envelope' => 'Express Commercial',
      'Express Mail Legal Flat Rate Envelope Hold For Pickup' => 'Express HFP Commercial',
      'Express Mail Padded Flat Rate Envelope' => 'Express Commercial',
      'Express Mail Padded Flat Rate Envelope Hold For Pickup' => 'Express HFP Commercial',
      'Priority Mail' => 'Priority Commercial',
      'Priority Mail Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Large Flat Rate Box' => 'Priority Commercial',
      'Priority Mail Large Flat Rate Box Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Medium Flat Rate Box' => 'Priority Commercial',
      'Priority Mail Medium Flat Rate Box Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Small Flat Rate Box' => 'Priority Commercial',
      'Priority Mail Small Flat Rate Box Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Regional Rate Box A' => 'Priority Commercial',
      'Priority Mail Regional Rate Box A Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Regional Rate Box B' => 'Priority Commercial',
      'Priority Mail Regional Rate Box B Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Regional Rate Box C' => 'Priority Commercial',
      'Priority Mail Regional Rate Box C Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Flat Rate Envelope' => 'Priority Commercial',
      'Priority Mail Flat Rate Envelope Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Legal Flat Rate Envelope' => 'Priority Commercial',
      'Priority Mail Legal Flat Rate Envelope Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Padded Flat Rate Envelope' => 'Priority Commercial',
      'Priority Mail Padded Flat Rate Envelope Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Gift Card Flat Rate Envelope' => 'Priority Commercial',
      'Priority Mail Gift Card Flat Rate Envelope Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Small Flat Rate Envelope' => 'Priority Commercial',
      'Priority Mail Small Flat Rate Envelope Hold For Pickup' => 'Priority HFP Commercial',
      'Priority Mail Window Flat Rate Envelope' => 'Priority Commercial',
      'Priority Mail Window Flat Rate Envelope Hold For Pickup' => 'Priority HFP Commercial',
      'First-Class Mail Parcel' => 'First-Class Mail',
      'First-Class Mail Large Envelope' => 'First-Class Mail',
      'First-Class Mail Letter' => 'First-Class Mail',
      'First-Class Package Service' => 'First Class Commercial',
      'First-Class Package Service Hold For Pickup' => 'First Class HFP Commercial',
      'Standard Post' => 'Parcel Post',
      'Media Mail' => 'Media',
      'Library Mail' => 'Library'
    );
    $this->type_to_container = array(
      'Express Mail' => '',
      'Express Mail Hold For Pickup' => '',
      'Express Mail Flat Rate Boxes' => 'Flat Rate Boxes',
      'Express Mail Flat Rate Boxes Hold For Pickup' => 'Flat Rate Boxes',
      'Express Mail Flat Rate Envelope' => 'Flat Rate Envelope',
      'Express Mail Flat Rate Envelope Hold For Pickup' => 'Flat Rate Envelope',
      'Express Mail Legal Flat Rate Envelope' => 'Legal Flat Rate Envelope',
      'Express Mail Legal Flat Rate Envelope Hold For Pickup' => 'Legal Flat Rate Envelope',
      'Express Mail Padded Flat Rate Envelope' => 'Padded Flat Rate Envelope',
      'Express Mail Padded Flat Rate Envelope Hold For Pickup' => 'Padded Flat Rate Envelope',
      'Priority Mail' => '',
      'Priority Mail Hold For Pickup' => '',
      'Priority Mail Large Flat Rate Box' => 'LG Flat Rate Box',
      'Priority Mail Large Flat Rate Box Hold For Pickup' => 'LG Flat Rate Box',
      'Priority Mail Medium Flat Rate Box' => 'MD Flat Rate Box',
      'Priority Mail Medium Flat Rate Box Hold For Pickup' => 'MD Flat Rate Box',
      'Priority Mail Small Flat Rate Box' => 'SM Flat Rate Box',
      'Priority Mail Small Flat Rate Box Hold For Pickup' => 'SM Flat Rate Box',
      'Priority Mail Regional Rate Box A' => 'Regional Rate Box A',
      'Priority Mail Regional Rate Box A Hold For Pickup' => 'Regional Rate Box A',
      'Priority Mail Regional Rate Box B' => 'Regional Rate Box B',
      'Priority Mail Regional Rate Box B Hold For Pickup' => 'Regional Rate Box B',
      'Priority Mail Regional Rate Box C' => 'Regional Rate Box C',
      'Priority Mail Regional Rate Box C Hold For Pickup' => 'Regional Rate Box C',
      'Priority Mail Flat Rate Envelope' => 'Flat Rate Envelope',
      'Priority Mail Flat Rate Envelope Hold For Pickup' => 'Flat Rate Envelope',
      'Priority Mail Legal Flat Rate Envelope' => 'Legal Flat Rate Envelope',
      'Priority Mail Legal Flat Rate Envelope Hold For Pickup' => 'Legal Flat Rate Envelope',
      'Priority Mail Padded Flat Rate Envelope' => 'Padded Flat Rate Envelope',
      'Priority Mail Padded Flat Rate Envelope Hold For Pickup' => 'Padded Flat Rate Envelope',
      'Priority Mail Gift Card Flat Rate Envelope' => 'Gift Card Flat Rate Envelope',
      'Priority Mail Gift Card Flat Rate Envelope Hold For Pickup' => 'Gift Card Flat Rate Envelope',
      'Priority Mail Small Flat Rate Envelope' => 'SM Flat Rate Envelope',
      'Priority Mail Small Flat Rate Envelope Hold For Pickup' => 'SM Flat Rate Envelope',
      'Priority Mail Window Flat Rate Envelope' => 'Window Flat Rate Envelope',
      'Priority Mail Window Flat Rate Envelope Hold For Pickup' => 'Window Flat Rate Envelope',
      'First-Class Mail Parcel' => '',
      'First-Class Mail Large Envelope' => '',
      'First-Class Mail Letter' => '',
      'First-Class Package Service' => '',
      'First-Class Package Service Hold For Pickup' => '',
      'Standard Post' => '',
      'Media Mail' => '',
      'Library Mail' => ''
    );
    $this->intl_types = array(
      'Global Express Guaranteed (GXG)**' => 'Global Express Guaranteed<sup>&reg;</sup> (GXG)**',
      'Express Mail International' => 'Express Mail<sup>&reg;</sup> International',
      'Priority Mail International' => 'Priority Mail<sup>&reg;</sup> International',
      'USPS GXG Envelopes**' => 'USPS GXG<sup>&trade;</sup> Envelopes**',
      'Express Mail International Flat Rate Boxes' => 'Express Mail<sup>&reg;</sup> International Flat Rate Boxes',
      'Express Mail International Flat Rate Envelope' => 'Express Mail<sup>&reg;</sup> International Flat Rate Envelope',
      'Express Mail International Legal Flat Rate Envelope' => 'Express Mail<sup>&reg;</sup> International Legal Flat Rate Envelope',
      'Express Mail International Padded Flat Rate Envelope' => 'Express Mail<sup>&reg;</sup> International Padded Flat Rate Envelope',
      'Priority Mail International Large Flat Rate Box' => 'Priority Mail<sup>&reg;</sup> International Large Flat Rate Box',
      'Priority Mail International Medium Flat Rate Box' => 'Priority Mail<sup>&reg;</sup> International Medium Flat Rate Box',
      'Priority Mail International Small Flat Rate Box**' => 'Priority Mail<sup>&reg;</sup> International Small Flat Rate Box**',
      'Priority Mail International DVD Flat Rate priced box**' => 'Priority Mail<sup>&reg;</sup> International DVD Flat Rate priced box**',
      'Priority Mail International Large Video Flat Rate priced box**' => 'Priority Mail<sup>&reg;</sup> International Large Video Flat Rate priced box**',
      'Priority Mail International Flat Rate Envelope**' => 'Priority Mail<sup>&reg;</sup> International Flat Rate Envelope**',
      'Priority Mail International Legal Flat Rate Envelope**' => 'Priority Mail<sup>&reg;</sup> International Legal Flat Rate Envelope**',
      'Priority Mail International Padded Flat Rate Envelope**' => 'Priority Mail<sup>&reg;</sup> International Padded Flat Rate Envelope**',
      'Priority Mail International Gift Card Flat Rate Envelope**' => 'Priority Mail<sup>&reg;</sup> International Gift Card Flat Rate Envelope**',
      'Priority Mail International Small Flat Rate Envelope**' => 'Priority Mail<sup>&reg;</sup> International Small Flat Rate Envelope**',
      'Priority Mail International Window Flat Rate Envelope**' => 'Priority Mail<sup>&reg;</sup> International Window Flat Rate Envelope**',
      'First-Class Package International Service**' => 'First-Class Package International Service<sup>&trade;</sup>**',
      'First-Class Mail International Large Envelope**' => 'First-Class Mail<sup>&reg;</sup> International Large Envelope**',
      'First-Class Mail International Letter**' => 'First-Class Mail<sup>&reg;</sup> International Letter**'
    );

**Comment by Evan-R** [comment]
did you reinstall the module before trying it?

**Comment by naps1saps** [comment]
I did not.  I have now and it is... working but i still have no FC letter for domestic.  If I uncheck everything and leave only FC letter, I get parcel post as an option :\

Actually I am not getting any envelope options at all: no priority or express flat rate envelopes either.

**Comment by Evan-R** [comment]
That may be to do with the weight or possibly dimensions of your test order; try it out on a very light order perhaps?

As far as changes needed, what version were you using before? You could just try running a diff comparison check if you prefer to go that route. The main changes are to do with the method names, which USPS decided to change in July (broke pre-existing modules)

**Comment by naps1saps** [comment]
Well looks like that was part of the problem got the flat rate envelopes now that i set "under 5lbs" to 0x0x0
However, I still do not have FC Letter xD this is too funny! i did set the size to 6x9x0.1 just in case and it still does not show up.  If i try to add my sorting code to domestic it breaks it giving the generic error if you want to use this method, contact the store owner. Adding it to international works great in comparison.

Weight for my item is at 0.01 lbs just fyi
International works flawlessly with the same item.  Not sure why domestic is giving me so many fits.

**Comment by naps1saps** [comment]
If I uncheck FC Mail and leave FC large env and letter, FC Mail is still present as an option and still no letter or large env.  I have a feeling it is interpreting FC letter and large env as FC Mail.

you can look at my usps.php file and config / store pages
http://epicdecals.com/usps.zip

**Comment by Evan-R** [comment]
I don't really have time to look at code in a zip file, although if you'd like to link me somewhere on github I could probably take a quick look. If you'd like to troubleshoot yourself, you could start by echoing out the quote name, here:

https://github.com/Evan-R/USPS-osCommerce/blob/master/includes/modules/shipping/usps.php#L1202

**Comment by naps1saps** [comment]
Yeah i don't have much time right now either but I'll get there eventually.  I'll update you when/if I find a fix for my problem.

**Comment by naps1saps** [comment]
Did you happen to download my usps.zip file and still have it?  My drive crashed while trying to back it up and corrupted my whole installation, images, etc...  all my work is gone basically.  Even the zip file is toast.  I thought I pasted my whole usps file in here but I guess I didn't :(

**Comment by Evan-R** [comment]
Sorry I did not - although the link you posted is still there. I'm working on another update now that will fix many of the methods, so keep an eye out on the repo over the next week or so ;)

**Comment by naps1saps** [comment]
Yeah that link is to a now corrupt file.  Oh well...  I had to fix my mod anyway so now it will be easier to start from scratch xD.  One customer every 4 months is not very motivating lol.  Thanks for your help though.
