### ISSUE TITLE
Adds weight and cost to zero weight items

### ISSUE THREAD

**Issue by kieranmullen** [Evan-R/USPS-osCommerce#7]
Since OS commerce cant really tell which items can fit into a flat rate envelope I thought about adding some items to the store which come with free shipping.  

They have no weight and no dimensions and yet when I check out it is adding a cost and a weight .01 oz.

It would be handy and smart if someone would put the version in the config page too. I dont know what I am running but it is pretty recent.
![git2](https://f.cloud.github.com/assets/5641990/1293130/66112986-305f-11e3-98c3-86498d3a5777.jpg)
![git1](https://f.cloud.github.com/assets/5641990/1293131/6617403c-305f-11e3-9bc2-be5f5fd4f37d.jpg)

**Comment by Evan-R** [comment]
under `configuration` -> `shipping/packaging` on your control panel you should see an option to set the package weight
