### ISSUE TITLE
	-2147219101 Missing value for Service.

### ISSUE THREAD

**Issue by sunrise-xx** [Evan-R/USPS-osCommerce#8]
I install it on osc 231/233 I have the following error:

United States Postal Service  (1 pkg, 0.50 lbs total) United States Postal Service  
    -2147219101 Missing value for Service.

**Comment by Evan-R** [comment]
This likely means that there is a service name mismatch, to resolve this you can edit the service properties set in the class constructor. You can narrow down what service is mismatching by disabling methods until it works. Then, consult the USPS api documentation (V3/V4 for domestic, V2 for international).

**Comment by zel777** [comment]
I'm getting the same error. Can you be a bit more precise with your explanation? Has there been a solution sunrise-xx?

**Comment by Evan-R** [comment]
It's quite likely that this error will be resolved (or you'll receive a helpful troubleshooting email) with `7.3.0` - I highly recommend that you upgrade
